services:
  - type: web
    name: Meet
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_TO_EMAIL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false